# Claude CI Failure Auto-Fix
#
# Copy this file to your repository's .github/workflows/on-ci-failure.yml
# Modify the workflow names in the 'workflows' array to match your CI workflows.
#
# Required org secrets:
#   - CLAUDE_CODE_OAUTH_TOKEN

name: CI Failure Auto-Fix

on:
  workflow_run:
    workflows: ["CI", "Test", "Build"]  # Modify this list to match your workflow names
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  actions: read
  issues: write
  id-token: write

jobs:
  auto-fix:
    if: github.event.workflow_run.conclusion == 'failure'
    uses: happyvertical/.github/.github/workflows/org-ci-failure-fix.yml@main
    with:
      workflow_name: ${{ github.event.workflow_run.name }}
      run_id: ${{ github.event.workflow_run.id }}
      head_branch: ${{ github.event.workflow_run.head_branch }}
      head_sha: ${{ github.event.workflow_run.head_sha }}
      pr_number: ${{ github.event.workflow_run.pull_requests[0].number || 0 }}
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
