# Claude Test Failure Analysis
#
# Copy this file to your repository's .github/workflows/on-test-failure.yml
# Modify the workflow names in the 'workflows' array to match your test workflows.
#
# Required org secrets:
#   - CLAUDE_CODE_OAUTH_TOKEN

name: Test Failure Analysis

on:
  workflow_run:
    workflows: ["Test", "CI"]  # Modify this list to match your test workflow names
    types: [completed]

permissions:
  contents: read
  issues: write
  pull-requests: write
  actions: read
  id-token: write

jobs:
  analyze:
    if: github.event.workflow_run.conclusion == 'failure'
    uses: happyvertical/.github/.github/workflows/org-test-analysis.yml@main
    with:
      run_id: ${{ github.event.workflow_run.id }}
      workflow_name: ${{ github.event.workflow_run.name }}
      pr_number: ${{ github.event.workflow_run.pull_requests[0].number || 0 }}
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
